version: "3.4"

services:

    php:
      build:
        context: .
        dockerfile: docker/Dockerfile-php
      container_name: load-php
      working_dir: /var/www/load-test/
      volumes:
        - .:/var/www/load-test/

    mysql:
        image: mysql:5.7
        container_name: load-mysql
        environment:
          MYSQL_USER: root
          MYSQL_PASSWORD: root
          MYSQL_DATABASE: load-test
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306

    nginx:
      image: nginx:alpine
      container_name: load-nginx
      volumes:
        - .:/var/www/load-test
        - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
        - 9000:80
